//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlameTradeSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingEntries
    {
        public int ID { get; set; }
        public int AccountID { get; set; }
        public Nullable<int> OriginModelID { get; set; }
        public Nullable<int> DocumentsID { get; set; }
        public Nullable<int> TransactionID { get; set; }
        public Nullable<double> CreditValue { get; set; }
        public Nullable<double> DebitValue { get; set; }
        public int IsVATEntry { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int AccountingCatalogID { get; set; }
        public Nullable<int> OriginModelDetailID { get; set; }
    
        public virtual AccountingCatalogs AccountingCatalogs { get; set; }
        public virtual AccountingEntriesModel AccountingEntriesModel { get; set; }
        public virtual Accounts Accounts { get; set; }
        public virtual Documents Documents { get; set; }
        public virtual DocumentTransactions DocumentTransactions { get; set; }
        public virtual AccountingEntriesModelDetails AccountingEntriesModelDetails { get; set; }
    }
}
