//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlameTradeSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingEntriesModelDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountingEntriesModelDetails()
        {
            this.AccountingEntries = new HashSet<AccountingEntries>();
        }
    
        public int ID { get; set; }
        public int AccountingEntriesModelID { get; set; }
        public int DebitAccountID { get; set; }
        public int CreditAccountID { get; set; }
        public double PercentOfValue { get; set; }
        public Nullable<int> VATAccountID { get; set; }
        public Nullable<double> VATPercent { get; set; }
        public int VatType { get; set; }
    
        public virtual AccountingEntriesModel AccountingEntriesModel { get; set; }
        public virtual Accounts Accounts { get; set; }
        public virtual Accounts Accounts1 { get; set; }
        public virtual Accounts Accounts2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountingEntries> AccountingEntries { get; set; }
    }
}
