//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlameTradeSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accounts()
        {
            this.AccountingEntriesModelDetails = new HashSet<AccountingEntriesModelDetails>();
            this.AccountingEntriesModelDetails1 = new HashSet<AccountingEntriesModelDetails>();
            this.AccountingEntriesModelDetails2 = new HashSet<AccountingEntriesModelDetails>();
            this.AccountingEntries = new HashSet<AccountingEntries>();
        }
    
        public int ID { get; set; }
        public string AccountCode { get; set; }
        public string AccountName { get; set; }
        public string AccountDescription { get; set; }
        public int AccountLevel { get; set; }
        public int AccountTypeID { get; set; }
        public int IsActive { get; set; }
        public int AccountGroupID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountingEntriesModelDetails> AccountingEntriesModelDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountingEntriesModelDetails> AccountingEntriesModelDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountingEntriesModelDetails> AccountingEntriesModelDetails2 { get; set; }
        public virtual AccountsGroups AccountsGroups { get; set; }
        public virtual AccountsType AccountsType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountingEntries> AccountingEntries { get; set; }
    }
}
