//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlameTradeSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentTransactions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentTransactions()
        {
            this.TransactionAttachments = new HashSet<TransactionAttachments>();
            this.TransactionLines = new HashSet<TransactionLines>();
            this.TransactionPersons = new HashSet<TransactionPersons>();
            this.TransactionsTransformations = new HashSet<TransactionsTransformations>();
            this.TransactionsTransformations1 = new HashSet<TransactionsTransformations>();
        }
    
        public int ID { get; set; }
        public int TransactionTypeID { get; set; }
        public int DocumentsID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<System.DateTime> ExpectedMatDate { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<System.DateTime> RequestedDeliveryDate { get; set; }
        public Nullable<double> Qty1 { get; set; }
        public Nullable<double> Qty2 { get; set; }
        public Nullable<double> Qty3 { get; set; }
        public Nullable<double> Value1 { get; set; }
        public Nullable<double> Value2 { get; set; }
        public Nullable<double> Value3 { get; set; }
        public int IsCompleated { get; set; }
        public int IsReady { get; set; }
        public int IsConfirmed { get; set; }
        public int IsDelivered { get; set; }
        public int UserID { get; set; }
        public System.DateTime CreationDateTime { get; set; }
        public Nullable<int> ColorID { get; set; }
        public int IsCanceled { get; set; }
    
        public virtual Colors Colors { get; set; }
        public virtual Documents Documents { get; set; }
        public virtual TransactionsType TransactionsType { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionAttachments> TransactionAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionLines> TransactionLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionPersons> TransactionPersons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionsTransformations> TransactionsTransformations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionsTransformations> TransactionsTransformations1 { get; set; }
    }
}
