//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlameTradeSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentSequences
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentSequences()
        {
            this.Documents = new HashSet<Documents>();
            this.Numbering = new HashSet<Numbering>();
            this.SequencesTransactions = new HashSet<SequencesTransactions>();
            this.DocumentSequencesProperties = new HashSet<DocumentSequencesProperties>();
            this.PossibleSequenceTransofrmation = new HashSet<PossibleSequenceTransofrmation>();
            this.PossibleSequenceTransofrmation1 = new HashSet<PossibleSequenceTransofrmation>();
            this.DocumentStringLines = new HashSet<DocumentStringLines>();
            this.DocumentsRolesRestrictions = new HashSet<DocumentsRolesRestrictions>();
        }
    
        public int ID { get; set; }
        public string SequenceName { get; set; }
        public string SequenceDescription { get; set; }
        public int IsReal { get; set; }
        public int TypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documents> Documents { get; set; }
        public virtual SequenceType SequenceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Numbering> Numbering { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SequencesTransactions> SequencesTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentSequencesProperties> DocumentSequencesProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PossibleSequenceTransofrmation> PossibleSequenceTransofrmation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PossibleSequenceTransofrmation> PossibleSequenceTransofrmation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentStringLines> DocumentStringLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentsRolesRestrictions> DocumentsRolesRestrictions { get; set; }
    }
}
