//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlameTradeSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialPlans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FinancialPlans()
        {
            this.FinancialPlanLines = new HashSet<FinancialPlanLines>();
            this.DocumentsFinancialPlan = new HashSet<DocumentsFinancialPlan>();
        }
    
        public int ID { get; set; }
        public int ProjectID { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string ContractNumber { get; set; }
        public string Comment { get; set; }
        public Nullable<double> CurrentOfferValue { get; set; }
        public Nullable<double> CurrentBudgetValue { get; set; }
        public Nullable<double> CurrentRealValue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialPlanLines> FinancialPlanLines { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentsFinancialPlan> DocumentsFinancialPlan { get; set; }
    }
}
