//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlameTradeSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class FunctionRoles
    {
        public int ID { get; set; }
        public int RoleID { get; set; }
        public int FunctionID { get; set; }
    
        public virtual Functions Functions { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
