//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlameTradeSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int ID { get; set; }
        public int TransactionLineID { get; set; }
        public int ItemID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int ItemPartitionID { get; set; }
        public Nullable<int> SecondPartitionID { get; set; }
        public Nullable<int> ColorID { get; set; }
        public double QTY { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Value { get; set; }
    
        public virtual Colors Colors { get; set; }
        public virtual Items Items { get; set; }
        public virtual Partitions Partitions { get; set; }
        public virtual Partitions Partitions1 { get; set; }
        public virtual TransactionLines TransactionLines { get; set; }
    }
}
