//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlameTradeSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceNumbering
    {
        public int ID { get; set; }
        public int number { get; set; }
        public Nullable<int> documentID { get; set; }
    
        public virtual Documents Documents { get; set; }
    }
}
