//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlameTradeSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Items()
        {
            this.Inventory = new HashSet<Inventory>();
            this.ItemsConfiguration = new HashSet<ItemsConfiguration>();
            this.ItemsConfiguration1 = new HashSet<ItemsConfiguration>();
            this.ReceiptLines = new HashSet<ReceiptLines>();
            this.TransactionLines = new HashSet<TransactionLines>();
            this.TransactionReceipt = new HashSet<TransactionReceipt>();
            this.ItemsParametersItems = new HashSet<ItemsParametersItems>();
            this.ItemsParametersItems1 = new HashSet<ItemsParametersItems>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public int DefaultMu { get; set; }
        public int DefaultPartition { get; set; }
        public int ItemsGroupID { get; set; }
        public int ItemCategory { get; set; }
        public Nullable<int> ForeignItemID { get; set; }
        public string SecondCode { get; set; }
        public Nullable<int> DefaultSupplierID { get; set; }
        public double StaticWeigth { get; set; }
        public double StaticSurface { get; set; }
        public double StaticHeight { get; set; }
        public double StaticWidth { get; set; }
        public double StaticLength { get; set; }
        public string PictureName { get; set; }
        public byte[] PictureData { get; set; }
        public int IsInactive { get; set; }
        public int DefaultSurfaceID { get; set; }
        public Nullable<int> FinancialCategoryID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory> Inventory { get; set; }
        public virtual ItemCategory ItemCategory1 { get; set; }
        public virtual Mu Mu { get; set; }
        public virtual Partitions Partitions { get; set; }
        public virtual ItemsGroups ItemsGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsConfiguration> ItemsConfiguration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsConfiguration> ItemsConfiguration1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptLines> ReceiptLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionLines> TransactionLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionReceipt> TransactionReceipt { get; set; }
        public virtual Partners Partners { get; set; }
        public virtual Surfaces Surfaces { get; set; }
        public virtual FinancialCategories FinancialCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsParametersItems> ItemsParametersItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsParametersItems> ItemsParametersItems1 { get; set; }
    }
}
