//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlameTradeSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogsEditRestrictedDocuments
    {
        public int ID { get; set; }
        public System.DateTime LogDate { get; set; }
        public int LogUserID { get; set; }
        public string LogReason { get; set; }
        public int LogAction { get; set; }
        public int DocumentID { get; set; }
        public Nullable<int> RestrictionControlUserID { get; set; }
        public Nullable<int> TargetRolesGroupID { get; set; }
        public Nullable<int> AnswerStatus { get; set; }
        public Nullable<int> RequestSessionID { get; set; }
        public Nullable<int> SendRequestNow { get; set; }
        public Nullable<System.DateTime> LogAllowedDeclinedDate { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual Documents Documents { get; set; }
    }
}
