//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlameTradeSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachinesInventory
    {
        public int ID { get; set; }
        public int TransactionLineID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int Direction { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<double> DeprRemainingValue { get; set; }
    
        public virtual TransactionLines TransactionLines { get; set; }
    }
}
