//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlameTradeSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Numbering
    {
        public int ID { get; set; }
        public int SequenceID { get; set; }
        public int MaxSequenceNumber { get; set; }
    
        public virtual DocumentSequences DocumentSequences { get; set; }
    }
}
