//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlameTradeSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonsRolesOfPersons
    {
        public int ID { get; set; }
        public int PersonsID { get; set; }
        public int RoleOfPersonID { get; set; }
    
        public virtual Persons Persons { get; set; }
        public virtual RoleOfPersons RoleOfPersons { get; set; }
    }
}
