//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlameTradeSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persons()
        {
            this.PartnerPersons = new HashSet<PartnerPersons>();
            this.PersonsRolesOfPersons = new HashSet<PersonsRolesOfPersons>();
            this.ProjectPersons = new HashSet<ProjectPersons>();
            this.TransactionPersons = new HashSet<TransactionPersons>();
            this.Users = new HashSet<Users>();
        }
    
        public int ID { get; set; }
        public string PersonName { get; set; }
        public string PersonMiddleName { get; set; }
        public string PersonSureName { get; set; }
        public string PersonAddress { get; set; }
        public string PersonEmail { get; set; }
        public string PersonPhone { get; set; }
        public string Comment { get; set; }
        public int PersonTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerPersons> PartnerPersons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonsRolesOfPersons> PersonsRolesOfPersons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectPersons> ProjectPersons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionPersons> TransactionPersons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users { get; set; }
        public virtual PersonsType PersonsType { get; set; }
    }
}
