//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlameTradeSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptModels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReceiptModels()
        {
            this.DocumentTransactions = new HashSet<DocumentTransactions>();
            this.ReceiptModelsItemCategories = new HashSet<ReceiptModelsItemCategories>();
            this.TransactionReceipt = new HashSet<TransactionReceipt>();
            this.ReceiptModelsItemsParameters = new HashSet<ReceiptModelsItemsParameters>();
            this.TransactionsType = new HashSet<TransactionsType>();
        }
    
        public int ID { get; set; }
        public string ModelName { get; set; }
        public string ModelDescription { get; set; }
        public int HasGeneralItems { get; set; }
        public int IsItemDirectRelated { get; set; }
        public int IsColorDirectRelated { get; set; }
        public int IsPartitionDIrectRelated { get; set; }
        public int IsSecondPartitionDirectRelated { get; set; }
        public int IsSurfaceDirectRelated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentTransactions> DocumentTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptModelsItemCategories> ReceiptModelsItemCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionReceipt> TransactionReceipt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptModelsItemsParameters> ReceiptModelsItemsParameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionsType> TransactionsType { get; set; }
    }
}
