//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlameTradeSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptLines
    {
        public int ID { get; set; }
        public int TransactionReceiptID { get; set; }
        public int ItemID { get; set; }
        public int ItemColorID { get; set; }
        public double ItemQTY { get; set; }
        public int ItemPartitionID { get; set; }
        public int SecondPartitionID { get; set; }
        public int SurfaceID { get; set; }
        public int ItemsParameterID { get; set; }
    
        public virtual Colors Colors { get; set; }
        public virtual Items Items { get; set; }
        public virtual Partitions Partitions { get; set; }
        public virtual Partitions Partitions1 { get; set; }
        public virtual TransactionReceipt TransactionReceipt { get; set; }
        public virtual Surfaces Surfaces { get; set; }
        public virtual ItemsParameters ItemsParameters { get; set; }
    }
}
