//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlameTradeSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptModelsItemsParameters
    {
        public int ID { get; set; }
        public int ReceiptModelID { get; set; }
        public int ItemsParameterID { get; set; }
    
        public virtual ItemsParameters ItemsParameters { get; set; }
        public virtual ReceiptModels ReceiptModels { get; set; }
    }
}
