//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlameTradeSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SequencesTransactions
    {
        public int ID { get; set; }
        public int SquenceID { get; set; }
        public int TransactionTypeID { get; set; }
    
        public virtual DocumentSequences DocumentSequences { get; set; }
        public virtual TransactionsType TransactionsType { get; set; }
    }
}
