//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlameTradeSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tasks()
        {
            this.TransactionPersons = new HashSet<TransactionPersons>();
        }
    
        public int ID { get; set; }
        public string TaksCode { get; set; }
        public string TaskName { get; set; }
        public string TaskDescription { get; set; }
        public int TaskType { get; set; }
        public Nullable<int> TaskCategory { get; set; }
        public Nullable<int> LineTypeDependacyID { get; set; }
    
        public virtual LinesType LinesType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionPersons> TransactionPersons { get; set; }
    }
}
