//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlameTradeSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionReceipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransactionReceipt()
        {
            this.ReceiptLines = new HashSet<ReceiptLines>();
            this.TransactionLines = new HashSet<TransactionLines>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ItemID { get; set; }
        public int ReceiptModelID { get; set; }
        public int ColorID { get; set; }
        public int PartitionID { get; set; }
        public int SecondPartitionID { get; set; }
        public int SurfaceID { get; set; }
    
        public virtual Items Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptLines> ReceiptLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionLines> TransactionLines { get; set; }
        public virtual Partitions Partitions { get; set; }
        public virtual Partitions Partitions1 { get; set; }
        public virtual ReceiptModels ReceiptModels { get; set; }
        public virtual Surfaces Surfaces { get; set; }
    }
}
