//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlameTradeSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionPersons
    {
        public int ID { get; set; }
        public int DocumentTransactionsID { get; set; }
        public int PersonID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public int TaskStatusID { get; set; }
        public string TaskCompletionLevel { get; set; }
        public Nullable<int> AssigningUserID { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    
        public virtual DocumentTransactions DocumentTransactions { get; set; }
        public virtual Persons Persons { get; set; }
        public virtual Tasks Tasks { get; set; }
        public virtual TaskStatuses TaskStatuses { get; set; }
    }
}
