//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlameTradeSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionsType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransactionsType()
        {
            this.DocumentTransactions = new HashSet<DocumentTransactions>();
            this.SequencesTransactions = new HashSet<SequencesTransactions>();
            this.DocumentSequencesProperties = new HashSet<DocumentSequencesProperties>();
            this.FinancialPlanLines = new HashSet<FinancialPlanLines>();
            this.FinancialPlanColors = new HashSet<FinancialPlanColors>();
            this.PossibleFinancialCategoryTransactionsType = new HashSet<PossibleFinancialCategoryTransactionsType>();
            this.PossibleSequenceTransformationsProperties = new HashSet<PossibleSequenceTransformationsProperties>();
            this.PossibleSequenceTransformationsProperties1 = new HashSet<PossibleSequenceTransformationsProperties>();
            this.TransactionNumbering = new HashSet<TransactionNumbering>();
        }
    
        public int ID { get; set; }
        public string TypeName { get; set; }
        public int TransactionMultiplier { get; set; }
        public int LinesRelation { get; set; }
        public int IsFinancialType { get; set; }
        public int DefaultSurfaceTypeID { get; set; }
        public int DefaultReceiptModelID { get; set; }
        public Nullable<int> DefaultAccountingEntryModelID { get; set; }
        public string Abbreviation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentTransactions> DocumentTransactions { get; set; }
        public virtual LinesType LinesType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SequencesTransactions> SequencesTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentSequencesProperties> DocumentSequencesProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialPlanLines> FinancialPlanLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialPlanColors> FinancialPlanColors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PossibleFinancialCategoryTransactionsType> PossibleFinancialCategoryTransactionsType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PossibleSequenceTransformationsProperties> PossibleSequenceTransformationsProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PossibleSequenceTransformationsProperties> PossibleSequenceTransformationsProperties1 { get; set; }
        public virtual SurfaceTypes SurfaceTypes { get; set; }
        public virtual ReceiptModels ReceiptModels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionNumbering> TransactionNumbering { get; set; }
        public virtual AccountingEntriesModel AccountingEntriesModel { get; set; }
    }
}
